spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-timeout: 5000
      idle-timeout: 20000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 5
    password: 12345678
    url: jdbc:mysql://localhost:3306/netty_file?characterEncoding=UTF-8
#    &queryInterceptors=com.minnovation.base.monitor.SqlTraceQueryInterceptor
    username: root